apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-docker
spec:
  project: default
  source:
    repoURL: '544167776152.dkr.ecr.eu-central-1.amazonaws.com'
    chart: 'react-docker'
    targetRevision: '0.2.0' 
    helm:
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true