apiVersion: v1
stringData:
  type:  helm
  enableOCI: "true"
  name: my-oci-charts
  password: ${aws_password}
  url: 544167776152.dkr.ecr.eu-central-1.amazonaws.com
  username: AWS
kind: Secret
metadata:
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
  name: my-oci-charts